team_aliases = {
    "mi": "Mumbai Indians",
    "mumbai": "Mumbai Indians",
    "mumbai indians": "Mumbai Indians",
    "rcb": "Royal Challengers Bangalore",
    "bangalore": "Royal Challengers Bangalore",
    "bglr": "Royal Challengers Bangalore",
    "csk": "Chennai Super Kings",
    "chennai": "Chennai Super Kings",
    "chennai super kings": "Chennai Super Kings",
    "dc": "Delhi Capitals",
    "delhi": "Delhi Capitals",
    "srh": "Sunrisers Hyderabad",
    "sunrisers": "Sunrisers Hyderabad",
    "kkr": "Kolkata Knight Riders",
    "kolkata": "Kolkata Knight Riders",
    "kings xi": "Punjab Kings",
    "kxip": "Punjab Kings",
    "punjab": "Punjab Kings",
    "rr": "Rajasthan Royals",
    "rajasthan": "Rajasthan Royals",
    "gujarat": "Gujarat Titans",
    "gt": "Gujarat Titans",
    "lsg": "Lucknow Super Giants",
    "lucknow": "Lucknow Super Giants"
}
